"""Init

Revision ID: 0d3f0d5fcdf2
Revises: 
Create Date: 2023-07-22 23:11:31.755817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3f0d5fcdf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('time_to_live', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN_1', 'PROCESSING_1', 'OPEN_2', 'PROCESSING_2', 'OPEN_3', 'PROCESSING_3', 'OPEN_4', 'PROCESSING_4', 'OPEN_5', 'PROCESSING_5', 'COOLING', name='alertstatus'), nullable=True),
    sa.Column('cooling_end_time', sa.DateTime(), nullable=True),
    sa.Column('time_triggered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    # ### end Alembic commands ###
